// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zaHK1fZCPypHzGJUKnafxHJgP49QmbY',
    appId: '1:224931912535:web:55d094022549d001617c12',
    messagingSenderId: '224931912535',
    projectId: 'grupp-3-57cc4',
    authDomain: 'grupp-3-57cc4.firebaseapp.com',
    storageBucket: 'grupp-3-57cc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlsdqkbKK93ociL9KQBTqlvBz23dh01_o',
    appId: '1:224931912535:android:a6db78fd1bf95750617c12',
    messagingSenderId: '224931912535',
    projectId: 'grupp-3-57cc4',
    storageBucket: 'grupp-3-57cc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Z0V2YOHKfNpxVc9FXEMsv-hgkQkaAd0',
    appId: '1:224931912535:ios:b647866e4b2d2fa5617c12',
    messagingSenderId: '224931912535',
    projectId: 'grupp-3-57cc4',
    storageBucket: 'grupp-3-57cc4.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );
}
